---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ueransim-gnb
  labels:
    app.kubernetes.io/version: "v3.2.6"
    app: ueransim
    component: gnb
spec:
  selector:
    matchLabels:
      app: ueransim
      component: gnb
  replicas: 1
  template:
    metadata:
      labels:
        app: ueransim
        component: gnb
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
            { "name": "n2network-ueransim-ueransim",
              "interface": "n2",
              "ips": [ "10.100.50.250/29" ],
              "gateway": [ "10.100.50.254" ]
            },
            { "name": "n3network-ueransim-ueransim",
              "interface": "n3",
              "ips": [ "10.0.0.20/24" ],
              "gateway": [ "10.0.0.1" ]
            }          
            ]'

    spec:
      containers:
      - image: towards5gs/ueransim-gnb:v3.2.6
        imagePullPolicy: IfNotPresent
        name: gnb
        ports:
        - name: gnb-ue
          containerPort: 4997
          protocol: UDP
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        command: ["./nr-gnb"]
        args: ["-c", "/ueransim/config/gnb-config.yaml"]  
        volumeMounts:
        - mountPath: /ueransim/config
          name: gnb-volume
        resources:
            requests:
              cpu: 250m
              memory: 256Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always

      volumes:
      - name: gnb-volume
        configMap:
          name: gnb-configmap
