---
apiVersion: v1
kind: Service
metadata:
  name: gnb-service
  labels:
    app.kubernetes.io/version: "v3.2.6"
    app: ueransim
    component: gnb
spec:
  type: ClusterIP
  ports:
    - name: gnb-ue
      port: 4997
      protocol: UDP
  selector:
    app: ueransim
    component: gnb
