apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: nephio-workload-cluster-sync
  namespace: config-management-system
  annotations:
    config.kubernetes.io/depends-on: apiextensions.k8s.io/CustomResourceDefinition/rootsyncs.configsync.gke.io
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/nephio-johnbelamaric/test-edge-01
    branch: main
    auth: none
