apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: porch-controllers-workloadidentitybinding
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - workloadidentitybindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - workloadidentitybindings/finalizers
  verbs:
  - update
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - workloadidentitybindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - iam.cnrm.cloud.google.com
  resources:
  - iampolicymembers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.cnrm.cloud.google.com
  resources:
  - iamserviceaccounts
  verbs:
  - get
  - list
  - watch
